language: cpp

sudo: required

git:
  submodules: false

cache:
  ccache: true
  directories:
  - ${HOME}/.ccache

services:
- docker

matrix:
  include:
  - env: BUILD_SCRIPT='gcc debug'

  - env: BUILD_SCRIPT='gcc release'

  - env: BUILD_SCRIPT='clang debug'

  - env: BUILD_SCRIPT='clang release'

  - env: BUILD_SCRIPT='clang asan'

  - env: BUILD_SCRIPT='clang ubsan'

  - env: BUILD_SCRIPT='gcc coverage'
    after_success:
    - >
      docker run -ti --rm -v ${PWD}:/code -e TRAVIS_JOB_ID="${TRAVIS_JOB_ID}" -e TRAVIS_BRANCH="${TRAVIS_BRANCH}"
      ozo_build coveralls --include include/ozo

before_install:
- sed -i 's;git@github.com:;https://github.com/;' .gitmodules
- git submodule update --init
- docker pull ubuntu:17.10
- scripts/build_docker_image_build.sh

script:
- scripts/build.sh docker ${BUILD_SCRIPT}
